name = "christianwhitmer"
main = "dist/_worker.js"
compatibility_date = "2026-02-13"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist"
binding = "ASSETS"

[[assets.rules]]
type = "CompiledContentType"
globs = ["**/*.wasm"]
fallthrough = true
